version: 0.2

# env:
  # variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run lint
      # - command
  build:
    commands:
      - npm run build
      # - command
  post_build:
    commands:
      - ls -al
      - aws s3 cp --recursive dist/ s3://devhaks-sample-s3
# artifacts:
  # files:
    # - location
  #name: $(date +%Y-%m-%d)
  # discard-paths: no
  # base-directory: dist
#cache:
  #paths:
    # - paths